###
GET http://34.127.63.92/ HTTP/1.1
###
POST http://34.127.63.92/data HTTP/1.1
Content-Type: application/json

{
    "Age": 10,
    "Asthma": true,
    "Breathing difficulty": true,
    "Cardiovascular": true,
    "Cough": true,
    "Diabetes": true,
    "Diarrhea": true,
    "Down Syndrome": true,
    "Fever": true,
    "Headache": true,
    "Hematologic (Blood Disease)": true,
    "Hypertension": true,
    "Immunosuppression": true,
    "Kidney disease": true,
    "Liver disease": true,
    "Low oxygen levels": true,
    "Male": true,
    "Myalgia": true,
    "Neurological": true,
    "Obesity": true,
    "Other diseases": true,
    "Pneumonia": true,
    "Pregnant": true,
    "Race": "Black",
    "Respiratory": true,
    "Sore throat": true,
    "Throat infection": true,
    "Tobacco": true,
    "Vomiting": true
 }
###